"use client";

import { useState } from "react";

const mots = [
  "Chat",
  "Chien",
  "Maison",
  "Soleil",
  "Lune",
  "Étoile",
  "Arbre",
  "Fleur",
  "Poisson",
  "Papillon",
  "Oiseau",
  "Voiture",
  "Bateau",
  "Avion",
  "Ballon",
  "Gâteau",
  "Bonbon",
  "Pomme",
  "Banane",
  "Lapin",
  "Coeur",
  "Nuage",
  "Cheval",
  "Vache",
  "Tortue",
  "Escargot",
  "Crocodile",
  "Requin",
  "Pingouin",
  "Château",
  "Bicyclette",
  "Fusée",
  "Robot",
  "Dinosaure",
  "Grenouille",
  "Éléphant",
  "Lion",
  "Tigre",
  "Singe",
  "Canard",
  "Chapeau",
  "Glace",
  "Clé",
  "Livre",
  "Échelle",
  "Montagne",
  "Plage",
  "Océan",
  "Île",
  "Laitue",
  "Citrouille",
  "Poire",
  "Cerise",
  "Fourmi",
  "Abeille",
  "Arrosoir",
  "Pirate",
  "Magicien",
  "Fée",
  "Chevalier",
  "Dragon",
  "Château fort",
  "Sorcière",
  "Balai",
  "Lunettes",
  "Téléphone",
  "Ordinateur",
  "Clown",
  "Parapluie",
  "Arc-en-ciel",
  "Feu d’artifice",
  "Étoile filante",
  "Coquillage",
  "Cerf-volant",
  "Chanson",
  "Musique",
  "Danse",
  "Chocolat",
  "Plante",
  "Feuille",
  "Chouette",
  "Hibou",
  "Poisson rouge",
  "Cerf",
  "Écureuil",
  "Hérisson",
  "Clown",
  "Chocolat chaud",
  "Feu de camp",
  "Montgolfière",
  "Sauterelle",
  "Dauphin",
  "Licorne",
  "Robot",
  "Loup",
  "Chaton",
  "Maison en pain d’épice",
  "Ballon de baudruche",
  "Panier",
  "Glissade",
  "Cerise",
  "Train",
  "Horloge",
  "Cheminée",
  "Miroir",
  "Montre",
  "Guitare",
  "Microphone",
  "Basket",
  "Souris",
  "Tournesol",
  "Carotte",
  "Lait",
  "Chaise",
  "Table",
  "Rideau",
  "Bougie",
  "Tapis",
  "Clé",
  "Valise",
  "Balle",
  "Plume",
  "Coccinelle",
  "Étoile de mer",
  "Sous-marin",
  "Fusée spatiale",
  "Planète",
  "Lanterne",
  "Cloche",
  "Cerf-volant",
  "Machine à écrire",
  "Chaussette",
  "Écharpe",
  "Casque",
  "Télévision",
  "Vélo",
  "Collier",
  "Épée",
  "Lance",
  "Bouclier",
  "Bateau pirate",
  "Île déserte",
  "Boussole",
  "Carte au trésor",
  "Sirène",
  "Dauphin",
  "Baleine",
  "Poisson clown",
  "Requin",
  "Raie",
  "Pieuvre",
  "Crabe",
  "Méduse",
  "Cactus",
  "Forêt",
  "Cascade",
  "Rivière",
  "Lac",
  "Montagne enneigée",
  "Désert",
  "Oasis",
  "Camion",
  "Ambulance",
  "Pompier",
  "Police",
  "Hélicoptère",
  "Avion de chasse",
  "Parapente",
  "Montgolfière",
  "Parachute",
  "Train à vapeur",
  "Métro",
  "Tramway",
  "Bus scolaire",
  "École",
  "Livre de contes",
  "Crayon",
  "Gomme",
  "Règle",
  "Sac à dos",
  "Trousse",
  "Tableau",
  "Chaise",
  "Bureau",
  "Ordinateur portable",
  "Souris d’ordinateur",
  "Clavier",
  "Écran",
  "Internet",
  "Application",
  "Jeu vidéo",
  "Console",
  "Télécommande",
  "Casque audio",
  "Microphone",
  "Guitare électrique",
  "Batterie",
  "Piano",
  "Flûte",
  "Violon",
  "Trompette",
  "Saxophone",
  "Tambour",
  "Batterie",
  "Haut-parleur",
  "Téléphone portable",
  "Tablette",
  "Écouteurs",
  "Montre connectée",
  "Drone",
  "Robot aspirateur",
  "Caméra",
  "Photo",
  "Selfie",
  "Portrait",
  "Paysage",
  "Ciel",
  "Nuage",
  "Arc-en-ciel",
  "Pluie",
  "Neige",
  "Vent",
  "Orage",
  "Foudre",
  "Tonnerre",
  "Flamme",
  "Feu",
  "Bougie",
  "Lantern",
  "Torche",
  "Lumière",
  "Ombre",
  "Reflet",
  "Miroir",
  "Fenêtre",
  "Porte",
  "Clé",
  "Serrure",
  "Mur",
  "Toit",
  "Cheminée",
  "Cloche",
  "Clocher",
  "Église",
  "Temple",
  "Mosquée",
  "Pagode",
  "Château",
  "Palais",
  "Tour",
  "Statue",
  "Pont",
  "Route",
  "Chemin",
  "Sentier",
  "Trottoir",
  "Pont suspendu",
  "Tunnel",
  "Ascenseur",
  "Escalier",
  "Échelle",
  "Balcon",
  "Jardin",
  "Parc",
  "Aire de jeux",
  "Balançoire",
  "Toboggan",
  "Bac à sable",
  "Bac à eau",
  "Piscine",
  "Plage",
  "Mer",
  "Océan",
  "Récif",
  "Corail",
  "Bateau",
  "Voilier",
  "Yacht",
  "Sous-marin",
  "Poisson",
  "Dauphin",
  "Baleine",
  "Requin",
  "Pieuvre",
  "Crabe",
  "Étoile de mer",
  "Méduse",
  "Algues",
  "Plante",
  "Arbre",
  "Fleur",
  "Buisson",
  "Herbe",
  "Champ",
  "Forêt",
  "Jungle",
  "Désert",
  "Montagne",
  "Volcan",
  "Grotte",
  "Rivière",
  "Cascade",
  "Lac",
  "Marais",
  "Oasis",
  "Île",
  "Ciel",
  "Soleil",
  "Lune",
  "Étoile",
  "Nuage",
  "Pluie",
  "Neige",
  "Vent",
  "Orage",
  "Foudre",
  "Tonnerre",
  "Flocon de neige",
  "Goutte d’eau",
  "Coquillage",
  "Papillon",
  "Abeille",
  "Fourmi",
  "Mouche",
  "Moustique",
  "Coccinelle",
  "Araignée",
  "Chenille",
  "Ver de terre",
  "Escargot",
  "Grenouille",
  "Crapaud",
  "Serpent",
  "Lézard",
  "Tortue",
  "Oiseau",
  "Aigle",
  "Faucon",
  "Hibou",
  "Chouette",
  "Pigeon",
  "Corbeau",
  "Moineau",
  "Canard",
  "Cygne",
  "Pingouin",
  "Pélican",
  "Perroquet",
  "Flamant rose",
  "Héron",
  "Cigogne",
  "Autruche",
  "Éléphant",
  "Girafe",
  "Lion",
  "Tigre",
  "Léopard",
  "Zèbre",
  "Rhinocéros",
  "Hippopotame",
  "Ours",
  "Loup",
  "Renard",
  "Chien",
  "Chat",
  "Cheval",
  "Âne",
  "Mouton",
  "Chèvre",
  "Vache",
  "Cochon",
  "Lapin",
  "Hamster",
  "Souris",
  "Rat",
  "Hérisson",
  "Castor",
  "Écureuil",
  "Marmotte",
  "Blaireau",
  "Chauve-souris",
  "Singe",
  "Gorille",
  "Orang-outan",
  "Babouin",
  "Kangourou",
  "Koala",
  "Panda",
  "Loutre",
  "Phoque",
  "Dauphin",
  "Baleine",
  "Requin",
  "Poisson-clown",
  "Raie",
  "Méduse",
  "Crabe",
  "Homard",
  "Étoile de mer",
  "Pieuvre",
  "Canard",
  "Oie",
  "Dinde",
  "Poule",
  "Coq",
  "Pigeon",
  "Perroquet",
  "Colibri",
  "Moineau",
  "Corbeau",
  "Hibou",
  "Chouette",
  "Faucon",
  "Aigle",
  "Vautour",
  "Autruche",
  "Manchot",
  "Pingouin",
  "Héron",
  "Flamant",
  "Pélican",
  "Cygne",
  "Élan",
  "Cerf",
  "Chevreuil",
  "Biche",
  "Sanglier",
  "Loutre",
  "Renard",
  "Loup",
  "Ours",
  "Marmotte",
  "Blaireau",
  "Chamois",
  "Bouquetin",
  "Lièvre",
  "Lapin",
  "Rat",
  "Souris",
  "Hérisson",
  "Fourmi",
  "Abeille",
  "Papillon",
  "Libellule",
  "Mouche",
  "Moustique",
  "Araignée",
  "Scorpion",
  "Escargot",
  "Ver de terre",
  "Coccinelle",
  "Cigale",
  "Sauterelle",
  "Criquet",
  "Guêpe",
  "Bourdon",
  "Chenille",
  "Papillon de nuit",
  "Mille-pattes",
  "Caméléon",
  "Gecko",
  "Lézard",
  "Iguane",
  "Tortue",
  "Serpent",
  "Vipère",
  "Cobra",
  "Python",
  "Boa",
  "Anaconda",
  "Crocodile",
  "Alligator",
  "Tortue de mer",
  "Tortue terrestre",
  "Dauphin",
  "Baleine bleue",
  "Orque",
  "Phoque",
  "Morse",
  "Narval",
  "Manchot empereur",
  "Poisson rouge",
  "Poisson-clown",
  "Requin marteau",
  "Raie manta",
  "Méduse",
  "Étoile de mer",
  "Homard",
  "Crabe",
  "Langouste",
  "Crevette",
  "Calmar",
  "Pieuvre",
  "Morue",
  "Bar",
  "Truite",
  "Saumon",
  "Anguille",
  "Perche"
];


export default function JeuPage() {
  const [motsRestants, setMotsRestants] = useState([...mots]);
  const [motAffiche, setMotAffiche] = useState("");

  function afficherMot() {
    if (motsRestants.length === 0) {
      setMotAffiche("Plus de mots !");
      return;
    }
    const index = Math.floor(Math.random() * motsRestants.length);
    const motChoisi = motsRestants[index];
    setMotAffiche(motChoisi);
    const nouveauxMots = motsRestants.filter((_, i) => i !== index);
    setMotsRestants(nouveauxMots);
  }

  return (
    <div style={{ 
      padding: "2rem", 
      backgroundColor: "#000", 
      color: "#fff", 
      textAlign: "center", 
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center"
    }}>
      <h1></h1>
      <button
        onClick={afficherMot}
        style={{
          fontSize: "2.5rem",
          padding: "1rem 3rem",
          borderRadius: "12px",
          backgroundColor: "#4CAF50",
          color: "white",
          border: "none",
          cursor: "pointer",
          marginTop: "2rem",
          userSelect: "none",
        }}
      >
        Afficher un mot
      </button>
      <div
        style={{
          marginTop: "5rem",
          fontSize: "4rem",
          fontWeight: "bold",
          minHeight: "5rem",
          color: "#fff",  // blanc pour bien contraster sur fond noir
        }}
      >
        {motAffiche}
      </div>
    </div>
  );
}
